Update 02-Especificação do Projeto.md
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #10
Opened 2024-04-09 16:29 UTC by EnriqueAlves

2024-04-09 16:43 UTC, 1alyciaoliveira requested changes
Ficou otimo, encontrei apenas alguns pontos pra ajustar:
- Nos perfis Estudante e Executivo, falta um ponto final na ultima frase.
- Nos 3 perfis, a necessidade 1 ta desalinhada com o resto do texto.

2024-04-09 21:42 UTC, AlexsanderGC approved these changes

2024-04-10 02:06 UTC, 1alyciaoliveira approved these changes

2024-04-10 02:06 UTC, BlueCalango approved these changes

2024-04-10 02:06 UTC, merged