modal-grafico
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #114
Opened 2024-05-29 16:17 UTC by PedroMaia14

2024-05-29 16:50 UTC, EnriqueAlves approved these changes

2024-05-29 23:39 UTC, AlexsanderGC approved these changes

2024-05-30 01:19 UTC, BlueCalango requested changes
O código base para a criação desse código para o gráfico está dando um conflito quando eu faço "git checkout editando-pagina-grafico" no VSCODE. Assim que eu testo o código a versão do HTML que está na branch é bem desatualizada. Não sei como isso pode ter acontecido, Alex olhou e na máquina dele também está com esse problema, estou com medo de aprovar e fazer uma alteração na Main para que fique igual ao código da branch. Pode ser só uma falta de compreensão minha de como essa parte funciona e não dê problema nenhum, mas, por conta dos problemas que tivemos na última entrega, estou tomando o máximo de cuidado possível.

2024-06-06 01:54 UTC, 1alyciaoliveira commented
Pull request vai ser fechado e tema vai ser tratado em outro por conflito de branch. https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal/pull/121

2024-06-06 01:54 UTC, closed without merging