Home html puc
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #44
Opened 2024-04-20 19:57 UTC by PedroMaia14

Criação do footer e texto adicionado"

2024-04-20 21:16 UTC, 1alyciaoliveira requested changes

2024-04-20 21:16 UTC, 1alyciaoliveira commented on codigo-fonte/home-certa.html
Falta semântica (o body deve estar dividido entre nav-main-footer)
Dentro do nav e do footer, necessitamos chamar o html correspondente.

<body>
    <header>
        <nav>

            <object data="navbar.html"
                type="text/html"
                style="height: 60px; width: 100%;">
            </object>

        </nav>
    </header>
    <main>
    ADICIONAR CODIGO AQUI
       </main>
    <footer>
        <object data="footer.html"
            type="text/html"
            style="height: 60px; width: 100%;">
        </object>
    </footer>
    
</body>
</html>

O titulo e Curriculo Ideal, ta como curriculo perfeito hehe

Os divs devem ter id ou classes pra uqe posam ser chamados no CSS,

Sobe as imagens de menina e mao, porfi :)

2024-04-20 21:16 UTC, 1alyciaoliveira commented on codigo-fonte/home.html
Se o correto e o outro arquivo, precisamos apagar esse :)

2024-04-21 22:29 UTC, 1alyciaoliveira approved these changes

2024-04-21 22:37 UTC, AlexsanderGC approved these changes

2024-04-22 00:53 UTC, BlueCalango approved these changes

2024-04-22 01:17 UTC, merged