codigo de signup
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #62
Opened 2024-04-24 01:21 UTC by andreaalvesvs

2024-04-24 03:08 UTC, 1alyciaoliveira commented on codigo-fonte/signup.html
> +            <input type="nome" id="nome" nome="nome">
O type do nome e do sobre nome deveria ser text

2024-04-24 03:09 UTC, 1alyciaoliveira commented on codigo-fonte/signup.html
> +    <img src="undraw_fingerprint_login_re_t71l (1).svg" alt="mulher segurando placa de impressão digital">
ajustar imagem que nao funciona nessa branch para evitar conflitos. Antes de dar push outra vez, faz um git fetch origin main e um git pull origin main, porfi.

2024-04-24 03:09 UTC, 1alyciaoliveira requested changes
Comentarios feitos no codigo. 

- [x] Revisar type de Nome e sobrenome
- [ ] Ajustar imagem

2024-04-25 01:48 UTC, AlexsanderGC approved these changes

2024-04-27 23:11 UTC, BlueCalango approved these changes

2024-04-27 23:42 UTC, 1alyciaoliveira approved these changes

2024-04-27 23:42 UTC, merged