revisao html e criacao css suas candidaturas
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #83
Opened 2024-05-02 00:03 UTC by AlexsanderGC

2024-05-02 01:47 UTC, 1alyciaoliveira requested changes

2024-05-02 01:47 UTC, 1alyciaoliveira commented on codigo-fonte/suascandidaturas.html
> +    <link rel="stylesheet" href="suascandidaturas+css.css">
o que é esse suascandidaturas+css.css?

No nav, o link de organize deve ser suascandidaturas.html e o signup signup.html

2024-05-02 01:47 UTC, 1alyciaoliveira commented on codigo-fonte/suascandidaturas.html
A posicao do botao de adicionar vaga tambem precisa ser ajustada

2024-05-02 01:47 UTC, 1alyciaoliveira commented on codigo-fonte/suascandidaturas.html
> +            <header class="suascandidaturas"> Suas candidaturas </header>
header nao é a tag correta, já foi usada pra nav. Acredito que seria um div mesmo.

2024-05-02 01:47 UTC, 1alyciaoliveira commented on codigo-fonte/suascandidaturas.html
O header nunca foi fechado.

2024-05-02 01:47 UTC, 1alyciaoliveira commented on codigo-fonte/suascandidaturas-style.css
O CSS tá bastante diferente do planejado, o que aconteceu?
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal/assets/108914238/d39084d6-8813-4bae-a39d-9fa3d7fc1a21)

2024-05-02 01:57 UTC, 1alyciaoliveira commented on codigo-fonte/suascandidaturas.html
> +                        <div class="card aplicado-1">
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal/assets/108914238/e43fad68-7702-40d0-a685-a69b83666ea5)
Por que esses elementos sao clicaveis?

2024-05-09 00:34 UTC, 1alyciaoliveira approved these changes

2024-05-09 00:34 UTC, PedroMaia14 approved these changes

2024-05-09 00:34 UTC, BlueCalango approved these changes

2024-05-09 00:34 UTC, andreaalvesvs approved these changes

2024-05-09 01:10 UTC, merged