index-nova-atualizada-bootstrap
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #84
Opened 2024-05-02 01:49 UTC by PedroMaia14

2024-05-02 02:21 UTC, 1alyciaoliveira requested changes

2024-05-02 02:21 UTC, 1alyciaoliveira commented on index.html
> +                    <li><a href="gerenciar-vagas.html">ORGANIZE</a>
o link de organize precisa ser o suascandidaturas.html eo de signup signup.html

2024-05-02 02:21 UTC, 1alyciaoliveira commented on index.html
> +    <link rel="stylesheet" href="navbar-footer-style.css">
o CSS do footer e do navbar nao funciona porque o arquivo nao esta dentro da pasta codigo fonte

2024-05-02 02:21 UTC, 1alyciaoliveira commented on index.html
> +                        <img src="img/menina.svg" alt="menina" class="img-fluid">
A imagem nao aparece porque o arquivo está fora da pasta codigo fonte

2024-05-02 02:21 UTC, 1alyciaoliveira commented on index.html
> +                                    <button type="button" class="btn btn-primary mb-0">APRENDA</button>
sao todos "a href", nao aplica o botao de aprenda. E precisam estar com os links corretos

2024-05-02 02:21 UTC, 1alyciaoliveira commented on index.html
> +                        <a href="#" class="btn btn-primary">CRIE</a>
falta o link do href

2024-05-02 14:06 UTC, PedroMaia14 commented on index.html
> +    <link rel="stylesheet" href="navbar-footer-style.css">
coloquei, o resto do css da pagina funcionou, mas o do footer e do css continuam do lado errado

2024-05-05 17:22 UTC, PedroMaia14 reviewed
Gráfico*

2024-05-06 01:22 UTC, 1alyciaoliveira requested changes

2024-05-06 01:22 UTC, 1alyciaoliveira commented on .vscode/launch.json
> +    // Use o IntelliSense para saber mais sobre os atributos possíveis.
O que é esse arquivo?

2024-05-06 01:22 UTC, 1alyciaoliveira commented on codigo-fonte/grafico.html
> +<head>
A página precisa ter navbar e footer como todas as outras, porfi. Também precisa usar a fonte correta.

2024-05-06 01:22 UTC, 1alyciaoliveira commented on codigo-fonte/grafico.html
> +    <style>
O style precisa ser criado a parte em um arquivo CSS.

2024-05-06 01:22 UTC, 1alyciaoliveira commented on codigo-fonte/grafico.html
> +        const ctx = document.getElementById('grafico1').getContext('2d');
Script precisa ser criado a parte em um arquivo JS

2024-05-06 23:44 UTC, AlexsanderGC approved these changes

2024-05-06 23:44 UTC, EnriqueAlves approved these changes

2024-05-06 23:44 UTC, 1alyciaoliveira commented
Approval sendo feito agora pra usar o codigo da home

2024-05-06 23:44 UTC, andreaalvesvs approved these changes

2024-05-06 23:45 UTC, 1alyciaoliveira approved these changes

2024-05-06 23:45 UTC, merged