revisando html css e adicionando js
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t8-pmv-ads-2024-1-e1-proj-curriculo-ideal pull request #90
Opened 2024-05-11 01:41 UTC by AlexsanderGC

2024-05-11 02:02 UTC, 1alyciaoliveira requested changes

2024-05-11 02:02 UTC, 1alyciaoliveira commented on codigo-fonte/suas-candidaturas/suas-candidaturas.js
> +/** help */
Me explica essa funcao? help a que? de onde vem essa message?

2024-05-11 02:02 UTC, 1alyciaoliveira commented on codigo-fonte/suas-candidaturas/suas-candidaturas.js
> +const cards = document.querySelectorAll('.card')
As constantes/variáveis globais devem estar na parte superior do código

2024-05-11 02:02 UTC, 1alyciaoliveira commented on codigo-fonte/suas-candidaturas/suas-candidaturas.js
> +function drag() {
Essa funcao aqui faz o que?

2024-05-11 02:02 UTC, 1alyciaoliveira commented on codigo-fonte/suas-candidaturas/suas-candidaturas.js
Coloca os comentários em portugues, porfa. Acho que fica mais explicativo.

2024-05-12 17:47 UTC, andreaalvesvs approved these changes

2024-05-12 18:28 UTC, 1alyciaoliveira approved these changes

2024-05-12 18:36 UTC, EnriqueAlves approved these changes

2024-05-12 21:13 UTC, AlexsanderGC commented on codigo-fonte/suas-candidaturas/suas-candidaturas.js
> +/** help */
ela está reduzindo o codigo das menssagens do log

2024-05-12 21:19 UTC, merged